# Goes with the example https://github.com/RailsApps/learn-rails

# Build with the application folder as argument:
# docker build -f Dockerfile.decoy [APP_FOLDER]

FROM ft-rails:on-build

RUN ["apt-get", "install", "-y", "nodejs"]
EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p" ,"3000"]